# Generated by Django 3.2.7 on 2021-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Profilbild'),
        ),
    ]
