# Generated by Django 3.2.7 on 2021-10-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_wish_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='visibility',
            new_name='visibility_to_owner',
        ),
    ]
